#!/bin/bash

set -euo pipefail
shopt -s nullglob

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <problem_id>" >&2
    exit 1
fi

problem_id="$1"
problem_dir="$problem_id"

mkdir -p "$problem_dir"

# 1. Generate the C++ solution file using leetcode-cli
leetcode edit "$problem_id" -l cpp

# 2. Gather data to fill out our template
solution_files=("$problem_dir/$problem_id".*.cpp)
link="<leetcode.com/problems/...>"
difficulty="<Difficulty>"
date_str=$(date +%F)

if ((${#solution_files[@]})); then
    filename=$(basename "${solution_files[0]}")
    
    # Extract the slug from the filename (e.g., "121.best-time-to-buy.cpp" -> "best-time-to-buy")
    slug=$(echo "$filename" | sed -E "s/^[0-9]+\.(.*)\.cpp$/\1/")
    link="https://leetcode.com/problems/$slug/"
    
    # Extract the difficulty level from the comment generated by leetcode-cli
    extracted_diff=$(grep -i "^// Level:" "${solution_files[0]}" | sed -E 's/.*Level: (.*)/\1/' | tr -d '\r')
    if [[ -n "$extracted_diff" ]]; then
        difficulty="$extracted_diff"
    fi
fi

# 3. Copy the template, swap placeholders using sed, and save to the problem folder
sed -e "s|{{PROBLEM_ID}}|$problem_id|g" \
    -e "s|{{LINK}}|$link|g" \
    -e "s|{{DIFFICULTY}}|$difficulty|g" \
    -e "s|{{DATE}}|$date_str|g" \
    templates/README.md > "$problem_dir/README.md"

# 4. Generate the empty test file
cat > "$problem_dir/$problem_id".tests.dat <<'EOF'
EOF

# 5. Process standard library inclusions
python3 - "$problem_dir" <<'PY'
from pathlib import Path
import sys

problem_dir = Path(sys.argv[1])

HEADER_BLOCK = """#if __has_include("leetcode.hpp")
#include "leetcode.hpp"
#elif __has_include("../leetcode.hpp")
#include "../leetcode.hpp"
#endif"""

for path in problem_dir.glob("*.cpp"):
    original = path.read_text(encoding="utf-8")

    # If header guard block is missing or old, normalize it
    if '#include "leetcode.hpp"' in original or '__has_include' in original:
        # Strip existing leetcode include blocks
        lines = original.splitlines()
        filtered = [l for l in lines if not ('leetcode.hpp' in l or '#if __has_include' in l or '#elif __has_include' in l or '#endif' in l and 'leetcode' in original)]
        updated = HEADER_BLOCK + "\n\n" + "\n".join(filtered).lstrip()
    else:
        updated = HEADER_BLOCK + "\n\n" + original

    updated = updated.replace('#include <stdio>', '#include <cstdio>')
    path.write_text(updated, encoding="utf-8")
PY