#!/bin/bash

set -euo pipefail
shopt -s nullglob

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <problem_id>" >&2
    exit 1
fi

problem_id="$1"
problem_dir="$problem_id"

mkdir -p "$problem_dir"

# 1. Generate the C++ solution file using leetcode-cli
leetcode edit "$problem_id" -l cpp

# 2. Gather data to fill out our template
solution_files=("$problem_dir/$problem_id".*.cpp)
link="<leetcode.com/problems/...>"
difficulty="<Difficulty>"
date_str=$(date +%F)

if ((${#solution_files[@]})); then
    filename=$(basename "${solution_files[0]}")
    
    # Extract the slug from the filename (e.g., "121.best-time-to-buy.cpp" -> "best-time-to-buy")
    slug=$(echo "$filename" | sed -E "s/^[0-9]+\.(.*)\.cpp$/\1/")
    link="https://leetcode.com/problems/$slug/"
    
    # Extract the difficulty level from the comment generated by leetcode-cli
    extracted_diff=$(grep -i "^// Level:" "${solution_files[0]}" | sed -E 's/.*Level: (.*)/\1/' | tr -d '\r')
    if [[ -n "$extracted_diff" ]]; then
        difficulty="$extracted_diff"
    fi
fi

# 3. Copy the template, swap placeholders using sed, and save to the problem folder
sed -e "s|{{PROBLEM_ID}}|$problem_id|g" \
    -e "s|{{LINK}}|$link|g" \
    -e "s|{{DIFFICULTY}}|$difficulty|g" \
    -e "s|{{DATE}}|$date_str|g" \
    templates/README.md > "$problem_dir/README.md"

# 4. Generate the empty test file
cat > "$problem_dir/$problem_id".tests.dat <<'EOF'
EOF

# 5. Process standard library inclusions
python3 - "$problem_dir" <<'PY'
from pathlib import Path
import sys

problem_dir = Path(sys.argv[1])

for path in problem_dir.glob("*.cpp"):
    original = path.read_text(encoding="utf-8")

    if "__has_include(\"leetcode.hpp\")" in original:
        continue

    if '#include "../../leetcode.hpp"' in original:
        updated = original.replace(
            '#include "../../leetcode.hpp"',
            '#if __has_include("leetcode.hpp")\n#include "leetcode.hpp"\n#endif',
        )
    elif '#include "leetcode.hpp"' in original:
        updated = original.replace(
            '#include "leetcode.hpp"',
            '#if __has_include("leetcode.hpp")\n#include "leetcode.hpp"\n#endif',
        )
    else:
        lines = original.splitlines()
        insert_at = 0
        while insert_at < len(lines) and (
            not lines[insert_at].strip() or lines[insert_at].lstrip().startswith("//")
        ):
            insert_at += 1

        prefix = [
            '#if __has_include("leetcode.hpp")',
            '#include "leetcode.hpp"',
            '#endif',
            '',
        ]
        updated_lines = lines[:insert_at] + prefix + lines[insert_at:]
        updated = "\n".join(updated_lines)
        if original.endswith("\n"):
            updated += "\n"

    updated = updated.replace('#include <stdio>', '#include <cstdio>')
    path.write_text(updated, encoding="utf-8")
PY