#!/bin/bash

set -euo pipefail
shopt -s nullglob

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <problem_id>" >&2
    exit 1
fi

problem_id="$1"
temp_dir="$problem_id"

mkdir -p "$temp_dir"

# 1. Generate the C++ solution file using leetcode-cli
leetcode edit "$problem_id" -l cpp

# 1.5 Capture ANY potential files generated in the root directory by leetcode-cli
# (Matches files like <id>.cpp, <id>.<slug>.tests, <id>.test.dat, or literal test.dat)
for file in "$problem_id".*; do
    if [[ -f "$file" && "$file" != "$0" ]]; then
        mv "$file" "$temp_dir/"
    fi
done

# 2. Gather data to fill out template and compute the target folder name
solution_files=("$temp_dir/$problem_id".*.cpp "$temp_dir"/*.cpp)
link="<leetcode.com/problems/...>"
difficulty="<Difficulty>"
date_str=$(date +%F)
target_dir="$temp_dir"

if ((${#solution_files[@]})); then
    filename=$(basename "${solution_files[0]}")
    
    # Extract the slug from the filename (e.g., "121.best-time-to-buy.cpp" -> "best-time-to-buy")
    slug=$(echo "$filename" | sed -E "s/^[0-9]+\.(.*)\.cpp$/\1/")
    link="https://leetcode.com/problems/$slug/"
    
    # Define folder name format: <problem_id>-<slug>
    target_dir="${problem_id}.${slug}"
    if [[ "$temp_dir" != "$target_dir" ]]; then
        mv "$temp_dir" "$target_dir"
    fi
    
    # Extract the difficulty level from the comment generated by leetcode-cli
    solution_path="$target_dir/$filename"
    extracted_diff=$(grep -i "^// Level:" "$solution_path" | sed -E 's/.*Level: (.*)/\1/' | tr -d '\r')
    if [[ -n "$extracted_diff" ]]; then
        difficulty="$extracted_diff"
    fi
fi

# 3. Copy the template, swap placeholders using sed, and save to the problem folder
if [[ -f "templates/README.md" ]]; then
    sed -e "s|{{PROBLEM_ID}}|$problem_id|g" \
        -e "s|{{LINK}}|$link|g" \
        -e "s|{{DIFFICULTY}}|$difficulty|g" \
        -e "s|{{DATE}}|$date_str|g" \
        templates/README.md > "$target_dir/README.md"
fi

# 4. Process test data generated by leetcode-cli -> <problem_id>.tests.dat
test_file=""

# Broadly search for the test file (catches .tests, .test.dat, .test, test.dat, etc.)
for candidate in "$target_dir/$problem_id"*test* "$target_dir"/*test*; do
    # Ensure it's a file and avoid matching the final target if it somehow already exists
    if [[ -f "$candidate" && "$candidate" != "$target_dir/$problem_id.tests.dat" ]]; then
        test_file="$candidate"
        break
    fi
done

if [[ -n "$test_file" ]]; then
    # Rename/move the verbose test file to <problem_id>.tests.dat
    mv "$test_file" "$target_dir/$problem_id.tests.dat"
    # Cleanup any remaining stray test files that leetcode-cli might have dumped
    for extra in "$target_dir"/*test*; do
        if [[ -f "$extra" && "$extra" != "$target_dir/$problem_id.tests.dat" ]]; then
            rm -f "$extra"
        fi
    done
else
    # Fallback: create empty test file only if absolutely no test file was produced
    touch "$target_dir/$problem_id.tests.dat"
fi

# 5. Process standard library inclusions
python3 - "$target_dir" <<'PY'
import sys
from pathlib import Path

problem_dir = Path(sys.argv[1])

HEADER_BLOCK = """#if __has_include("leetcode.hpp")
#include "leetcode.hpp"
#elif __has_include("../leetcode.hpp")
#include "../leetcode.hpp"
#endif"""

for path in problem_dir.glob("*.cpp"):
    original = path.read_text(encoding="utf-8")

    # If header guard block is missing or old, normalize it
    if '#include "leetcode.hpp"' in original or '__has_include' in original:
        lines = original.splitlines()
        filtered = [l for l in lines if not ('leetcode.hpp' in l or '#if __has_include' in l or '#elif __has_include' in l or '#endif' in l and 'leetcode' in original)]
        updated = HEADER_BLOCK + "\n\n" + "\n".join(filtered).lstrip()
    else:
        updated = HEADER_BLOCK + "\n\n" + original

    updated = updated.replace('#include <stdio>', '#include <cstdio>')
    path.write_text(updated, encoding="utf-8")
PY